const FETCH_HEADERS={"User-Agent":"FPL-AY/1.0","Accept":"application/json"};
const PRICE_APIS=["https://www.fplpricechanges.com/api/players","https://www.fplstatistics.co.uk/api/players"];
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8",...headers}})}
async function fplJson(path){const r=await fetch("https://fantasy.premierleague.com/api/"+path,{headers:FETCH_HEADERS});if(!r.ok)throw new Error("FPL API HTTP "+r.status);return r.json()}
function norm(v){const n=Number(v);return Number.isFinite(n)?n:null}
function predictorSource(raw){const src=raw&&raw.players?raw.players:raw&&raw.data?raw.data:raw;const players=Array.isArray(src)?src:[];const out={};for(const p of players){const id=p&&p.id;const progress=norm(p&&p.progress!=null?p.progress:(p&&p.price_change_percent!=null?p.price_change_percent:p&&p.predictedProgress));if(id!=null&&progress!==null)out[String(id)]={progress,predictedProgress:progress,likelihood:p&&p.likelihood!=null?norm(p.likelihood):null}}return out}
async function handleFpl(url){const path=url.searchParams.get("path")||"";if(!path)return json({error:"Missing path"},400);try{return json(await fplJson(path),200,{"Cache-Control":"no-store"})}catch(e){return json({error:String(e)},502)}}
async function handlePriceData(){let last=null;for(const ep of PRICE_APIS){try{const r=await fetch(ep,{headers:{...FETCH_HEADERS,"Cache-Control":"no-cache"}});if(!r.ok)throw new Error(ep+" returned HTTP "+r.status);const p=predictorSource(await r.json());if(Object.keys(p).length)return json({players:p,source:ep},200,{"Cache-Control":"public, max-age=60"})}catch(e){last=e}}try{const b=await fplJson("bootstrap-static/"),players={};for(const p of b.elements||[]){const progress=norm(p.price_change_percent);if(progress!==null)players[String(p.id)]={progress,predictedProgress:progress,likelihood:null}}if(Object.keys(players).length)return json({players,source:"fpl-bootstrap"},200,{"Cache-Control":"public, max-age=60"})}catch(e){last=e}return json({error:String(last||"Price predictor unavailable"),players:{}},502,{"Cache-Control":"no-store"})}
async function handleTeam(url){const id=Number.parseInt(url.searchParams.get("id")||"",10);if(!Number.isInteger(id)||id<=0)return json({error:"Invalid FPL team id"},400);try{const entry=await fplJson("entry/"+id+"/"),gw=Number.parseInt(String(entry.current_event||""),10);if(!Number.isInteger(gw)||gw<1)throw new Error("FPL team has no current gameweek");let picks=[];let gameweek=gw;try{const c=await fplJson("entry/"+id+"/event/"+gw+"/picks/");picks=Array.isArray(c.picks)?c.picks:[]}catch(_){}if(!picks.length&&gw>1)try{const p=await fplJson("entry/"+id+"/event/"+(gw-1)+"/picks/");picks=Array.isArray(p.picks)?p.picks:[];if(p.picks.length)gameweek=gw-1}catch(_){}if(picks.length!==15)throw new Error("FPL returned "+picks.length+" players instead of 15");return json({id,name:entry.name||"",value:entry.last_deadline_value||entry.value||0,bank:entry.last_deadline_bank||entry.bank||0,currentGameweek:gw,gameweek,picks:picks.map(p=>Number(p.element))},200,{"Cache-Control":"public, max-age=30"})}catch(e){return json({error:String(e)},502)}}
async function handleAsset(request,env){const r=await env.ASSETS.fetch(request);const ct=r.headers.get("content-type")||"";if(!r.ok||!ct.includes("text/html"))return r;let html=await r.text();const pathname=new URL(request.url).pathname;["jersey-fix.js","mobile-scroll-fix.js","pwa-enhance.js","team-menu.js","transfers-nav.js"].forEach(s=>{if(!html.includes("/"+s))html=html.replace(/<\/body>/i,'<script src="/'+s+'"></script></body>')});if(pathname==="/transfer"||pathname==="/transfers"||pathname==="/transfers.html"||pathname==="/transfers/index.html")html=html.replace(/<\/head>/i,'<link rel="stylesheet" href="/transfers-pitch.css"></head>');const h=new Headers(r.headers);h.delete("content-length");return new Response(html,{status:r.status,statusText:r.statusText,headers:h})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/fpl")return handleFpl(url);if(url.pathname==="/price-data")return handlePriceData();if(url.pathname==="/team")return handleTeam(url);if(url.pathname==="/transfer")return handleAsset(new Request(new URL("/transfers/index.html",url),request),env);if(url.pathname==="/transfers")return handleAsset(new Request(new URL("/transfers/index.html",url),request),env);if(url.pathname==="/transfers.html")return handleAsset(request,env);if(url.pathname==="/"||url.pathname==="/index.html")return handleAsset(request,env);return env.ASSETS.fetch(request)}}