const FPL_API="https://fantasy.premierleague.com/api/";
const PRICE_APIS=["https://livefpl.us/api/prices.json","https://www.livefpl.net/api/prices.json"];
const JSON_HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Content-Type":"application/json"};
const FETCH_HEADERS={"User-Agent":"Mozilla/5.0 (compatible; PriceWatch/1.0)","Accept":"application/json, text/plain, */*","Referer":"https://www.livefpl.net/prices"};
function json(body,status=200,extra={}){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...extra}})}
async function fplJson(path){const r=await fetch(FPL_API+path,{headers:FETCH_HEADERS});if(!r.ok)throw new Error("FPL returned HTTP "+r.status);return r.json()}
async function handleFpl(url){const p=String(url.searchParams.get("path")||"bootstrap-static/").replace(/^https?:\/\/[^/]+\/api\//i,"").replace(/^\/+/,"");const allowed=/^(bootstrap-static\/|element-summary\/\d+\/?|entry\/\d+\/?|entry\/\d+\/(?:history|transfers)\/?|entry\/\d+\/event\/\d+\/picks\/?)$/;if(!allowed.test(p))return json({error:"Unsupported FPL API path"},400);try{const r=await fetch(FPL_API+p,{headers:FETCH_HEADERS});return new Response(await r.text(),{status:r.status,headers:{...JSON_HEADERS,"Cache-Control":p==="bootstrap-static/"?"public, max-age=60":"public, max-age=30"}})}catch(e){return json({error:String(e)},502)}}
function norm(v){const n=Number(v);return Number.isFinite(n)?(Math.abs(n)>5?n/100:n):null}
function predictorSource(raw){const src=raw&&raw.players?raw.players:raw&&raw.data?raw.data:raw;const players={};const recs=Array.isArray(src)?src.map(x=>[x&&(x.id??x.element_id??x.player_id),x]):Object.entries(src||{});recs.forEach(([k,x])=>{if(!x||typeof x!=="object")return;const id=Number(x.id??x.element_id??x.player_id??k);if(!Number.isInteger(id)||id<=0)return;const progress=norm(x.progress??x.progress_now??x.current_progress??x.progress_now_pct),predictedProgress=norm(x.progress_tonight??x.predicted_progress??x.predictedProgress??x.prediction??progress),likelihood=Number.isFinite(Number(x.likelihood))?Number(x.likelihood):null;if(progress!==null||predictedProgress!==null)players[String(id)]={progress,predictedProgress,likelihood}});return players}
async function handlePriceData(){let last=null;for(const ep of PRICE_APIS){try{const r=await fetch(ep,{headers:{...FETCH_HEADERS,"Cache-Control":"no-cache"}});if(!r.ok)throw new Error(ep+" returned HTTP "+r.status);const p=predictorSource(await r.json());if(Object.keys(p).length)return json({players:p,source:ep},200,{"Cache-Control":"public, max-age=60"})}catch(e){last=e}}try{const b=await fplJson("bootstrap-static/"),players={};for(const p of b.elements||[]){const progress=norm(p.price_change_percent);if(progress!==null)players[String(p.id)]={progress,predictedProgress:progress,likelihood:null}}if(Object.keys(players).length)return json({players,source:"fpl-bootstrap"},200,{"Cache-Control":"public, max-age=60"})}catch(e){last=e}return json({error:String(last||"Price predictor unavailable"),players:{}},502,{"Cache-Control":"no-store"})}
async function handleTeam(url){const id=Number.parseInt(url.searchParams.get("id")||"",10);if(!Number.isInteger(id)||id<=0)return json({error:"Invalid FPL team id"},400);try{const entry=await fplJson("entry/"+id+"/"),gw=Number.parseInt(String(entry.current_event||""),10);if(!Number.isInteger(gw)||gw<1)throw new Error("FPL team has no current gameweek");let picks=[];let gameweek=gw;try{const c=await fplJson("entry/"+id+"/event/"+gw+"/picks/");picks=Array.isArray(c.picks)?c.picks:[]}catch(_){}if(!picks.length&&gw>1)try{const p=await fplJson("entry/"+id+"/event/"+(gw-1)+"/picks/");picks=Array.isArray(p.picks)?p.picks:[];if(picks.length)gameweek=gw-1}catch(_){}if(picks.length!==15)throw new Error("FPL returned "+picks.length+" players instead of 15");return json({id,name:entry.name||"",value:entry.last_deadline_value||entry.value||0,bank:entry.last_deadline_bank||entry.bank||0,currentGameweek:gw,gameweek,picks:picks.map(p=>Number(p.element))},200,{"Cache-Control":"public, max-age=30"})}catch(e){return json({error:String(e)},502)}}
async function handleAsset(request,env){const r=await env.ASSETS.fetch(request);const ct=r.headers.get("content-type")||"";if(!r.ok||!ct.includes("text/html"))return r;let html=await r.text();["jersey-fix.js","mobile-scroll-fix.js","pwa-enhance.js","team-menu.js","transfers-nav.js"].forEach(s=>{if(!html.includes("/"+s))html=html.replace(/<\/body>/i,'<script src="/'+s+'"></script></body>')});const h=new Headers(r.headers);h.delete("content-length");return new Response(html,{status:r.status,statusText:r.statusText,headers:h})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/fpl")return handleFpl(url);if(url.pathname==="/price-data")return handlePriceData();if(url.pathname==="/team")return handleTeam(url);if(url.pathname==="/transfer")return handleAsset(new Request(new URL("/transfer/index.html",url),request),env);if(url.pathname==="/transfers")return handleAsset(new Request(new URL("/transfer/index.html",url),request),env);if(url.pathname==="/transfers.html")return handleAsset(request,env);if(url.pathname==="/"||url.pathname==="/index.html")return handleAsset(request,env);return env.ASSETS.fetch(request)}}